In [23]:
import numpy as np
import pandas as pd
import math

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
zp

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [3]:
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
ks


array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [4]:
cov = (zp*ks).mean() - zp.mean() * ks.mean()
cov

9157.839999999997

In [5]:
np.cov(zp, ks)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [6]:
np.cov(zp, ks)[0,1]

10175.377777777776

In [7]:
z = np.cov(zp, ks, ddof = 0)[0,1]
z

9157.84

In [8]:
x = pd.DataFrame({'zp' : zp, 'ks' : ks}, columns = ['zp', 'ks'])
x

zp   ks
0   35  401
1   45  574
2  190  874
3  200  919
4   40  459
5   70  739
6   54  653
7  150  902
8  120  746
9  110  832

In [9]:
y = x.cov().values[0,1]
y

10175.377777777776

In [10]:
x.corr()

zp       ks
zp  1.00000  0.88749
ks  0.88749  1.00000

In [11]:
x1 = ks.std(ddof = 1)
x1

183.99544076477068

In [12]:
x2 = zp.std(ddof = 1)
x2

62.31318747531162

In [13]:
y / (x1 * x2)

0.887490092073916

In [14]:
z / (ks.std() * zp.std())

0.8874900920739162

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [16]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [18]:
x = iq.mean()
x

118.1

In [19]:
alpha = 0.025

In [20]:
t = 2.262

In [21]:
x_1 = x + ((t * (iq.std(ddof=1))) / ((10)**0.5))
x_1

125.64339223691834

In [22]:
x_2 = x - ((t * (iq.std(ddof=1))) / ((10)**0.5))
x_2

110.55660776308164

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [26]:
std = math.sqrt(25)
std

5.0

In [27]:
n = 27

In [28]:
mu = 174.2

In [29]:
z = 1.96

In [30]:
x_1 = mu - (z * std/(n)**0.5)
x_1

172.31398912064722

In [31]:
x_2 = mu + (z * std/((n)**0.5))
x_2

176.08601087935276